# Generated by Django 5.0.3 on 2024-12-27 06:49

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user', primary_key=True, serialize=False)),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Auto-generated username for the user.', max_length=150, unique=True, verbose_name='username')),
                ('email_verified', models.BooleanField(default=False, help_text='Designates whether this user has verified their email address.', verbose_name='email verified')),
                ('email_verification_token', models.CharField(blank=True, help_text='Token for verifying email address', max_length=200)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, help_text='When the verification email was last sent', null=True)),
                ('password_reset_token', models.CharField(blank=True, help_text='Token for password reset', max_length=200)),
                ('password_reset_sent_at', models.DateTimeField(blank=True, help_text='When the password reset email was sent', null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last login', null=True)),
                ('login_attempts', models.PositiveIntegerField(default=0, help_text='Number of failed login attempts')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Account locked until this time', null=True)),
                ('avatar', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'indexes': [models.Index(fields=['email'], name='appauth_app_email_52a081_idx'), models.Index(fields=['username'], name='appauth_app_usernam_b36baf_idx'), models.Index(fields=['email_verified'], name='appauth_app_email_v_544426_idx')],
            },
        ),
    ]
