# Generated by Django 5.0.3 on 2025-01-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_message_file_remove_message_file_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='original_text',
        ),
        migrations.AddField(
            model_name='messagecontent',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
