# Generated by Django 5.0.3 on 2024-07-30 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_chat_remove_message_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_pair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.messagepair'),
        ),
    ]
