# Generated by Django 5.0.3 on 2025-01-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_token_count_tokenusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
