# Generated by Django 5.0.3 on 2025-01-13 22:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_edited_at_message_hidden_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenusage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='messagepair',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='savedsystemprompt',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tokenusage',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='chat',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.messagepair'),
        ),
    ]
