# Generated by Django 5.0.3 on 2025-05-23 04:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_remove_chat_uuid_alter_chat_id_alter_message_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(help_text='AI-generated summary of the user information')),
                ('raw_content', models.TextField(help_text='Raw extracted content from the conversation')),
                ('confidence_score', models.FloatField(default=0.8, help_text='AI confidence in the extracted information (0-1)')),
                ('category', models.CharField(choices=[('personal', 'Personal Information'), ('preferences', 'Preferences & Interests'), ('work', 'Work & Professional'), ('goals', 'Goals & Aspirations'), ('relationships', 'Relationships'), ('lifestyle', 'Lifestyle & Habits'), ('technical', 'Technical Skills & Knowledge'), ('other', 'Other')], default='other', max_length=50)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether user has confirmed this information')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this memory should be used in future conversations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_referenced', models.DateTimeField(blank=True, help_text='When this memory was last used in a conversation', null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_memories', to='chat.chat')),
                ('source_message_pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.messagepair')),
                ('tags', models.ManyToManyField(blank=True, related_name='memories', to='chat.memorytag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='chat_userme_user_id_a9f44e_idx'), models.Index(fields=['user', 'is_active'], name='chat_userme_user_id_a63c36_idx'), models.Index(fields=['created_at'], name='chat_userme_created_3d8dbf_idx')],
            },
        ),
    ]
