# Generated by Django 5.0.3 on 2025-05-09 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototypes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prototype',
            name='html_content',
        ),
        migrations.CreateModel(
            name='PrototypeVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prototype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='prototypes.prototype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrototypeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('edit_prompt', models.TextField(blank=True, null=True)),
                ('html_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='prototypes.prototypevariant')),
            ],
            options={
                'ordering': ['version_number'],
                'unique_together': {('variant', 'version_number')},
            },
        ),
    ]
